const mongoose = require("mongoose");
const { faker } = require("@faker-js/faker");
const { Hobby, User } = require("../models");
require("dotenv").config();

const seedDb = async () => {
	// TODO: fix link so .env links properly. template literal doesn't seem to work?
	await mongoose.connect(
		`mongodb+srv://${process.env.DB_USERNAME}:${process.env.DB_PASSWORD}@cluster0.o20dk.mongodb.net/friender_DB?retryWrites=true&w=majority`
	);
	await Hobby.deleteMany({});
	await User.deleteMany({});

	const usersToCreate = [
		{
			firstName: faker.name.firstName(),
			lastName: faker.name.lastName(),
			email: faker.internet.email(),
			password: faker.internet.password(),
			gender: faker.name.gender(true),
			city: faker.address.city(),
			age: faker.mersenne.rand(100, 18),
			description: faker.lorem.sentence(),
			photo: faker.image.people(240),
		},
		{
			firstName: faker.name.firstName(),
			lastName: faker.name.lastName(),
			email: faker.internet.email(),
			password: faker.internet.password(),
			gender: faker.name.gender(true),
			city: faker.address.city(),
			age: faker.mersenne.rand(100, 18),
			description: faker.lorem.sentence(),
			photo: faker.image.people(240),
		},
		{
			firstName: faker.name.firstName(),
			lastName: faker.name.lastName(),
			email: faker.internet.email(),
			password: faker.internet.password(),
			gender: faker.name.gender(true),
			city: faker.address.city(),
			age: faker.mersenne.rand(100, 18),
			description: faker.lorem.sentence(),
			photo: faker.image.people(240),
		},
		{
			firstName: faker.name.firstName(),
			lastName: faker.name.lastName(),
			email: faker.internet.email(),
			password: faker.internet.password(),
			gender: faker.name.gender(true),
			city: faker.address.city(),
			age: faker.mersenne.rand(100, 18),
			description: faker.lorem.sentence(),
			photo: faker.image.people(240),
		},
		{
			firstName: faker.name.firstName(),
			lastName: faker.name.lastName(),
			email: faker.internet.email(),
			password: faker.internet.password(),
			gender: faker.name.gender(true),
			city: faker.address.city(),
			age: faker.mersenne.rand(100, 18),
			description: faker.lorem.sentence(),
			photo: faker.image.people(240),
		},
		{
			firstName: faker.name.firstName(),
			lastName: faker.name.lastName(),
			email: faker.internet.email(),
			password: faker.internet.password(),
			gender: faker.name.gender(true),
			city: faker.address.city(),
			age: faker.mersenne.rand(100, 18),
			description: faker.lorem.sentence(),
			photo: faker.image.people(240),
		},
		{
			firstName: faker.name.firstName(),
			lastName: faker.name.lastName(),
			email: faker.internet.email(),
			password: faker.internet.password(),
			gender: faker.name.gender(true),
			city: faker.address.city(),
			age: faker.mersenne.rand(100, 18),
			description: faker.lorem.sentence(),
			photo: faker.image.people(240),
		},
		{
			firstName: faker.name.firstName(),
			lastName: faker.name.lastName(),
			email: faker.internet.email(),
			password: faker.internet.password(),
			gender: faker.name.gender(true),
			city: faker.address.city(),
			age: faker.mersenne.rand(100, 18),
			description: faker.lorem.sentence(),
			photo: faker.image.people(240),
		},
		{
			firstName: faker.name.firstName(),
			lastName: faker.name.lastName(),
			email: faker.internet.email(),
			password: faker.internet.password(),
			gender: faker.name.gender(true),
			city: faker.address.city(),
			age: faker.mersenne.rand(100, 18),
			description: faker.lorem.sentence(),
			photo: faker.image.people(240),
		},
		{
			firstName: faker.name.firstName(),
			lastName: faker.name.lastName(),
			email: faker.internet.email(),
			password: faker.internet.password(),
			gender: faker.name.gender(true),
			city: faker.address.city(),
			age: faker.mersenne.rand(100, 18),
			description: faker.lorem.sentence(),
			photo: faker.image.people(240),
		},
		{
			firstName: faker.name.firstName(),
			lastName: faker.name.lastName(),
			email: faker.internet.email(),
			password: faker.internet.password(),
			gender: faker.name.gender(true),
			city: faker.address.city(),
			age: faker.mersenne.rand(100, 18),
			description: faker.lorem.sentence(),
			photo: faker.image.people(240),
		},
		{
			firstName: faker.name.firstName(),
			lastName: faker.name.lastName(),
			email: faker.internet.email(),
			password: faker.internet.password(),
			gender: faker.name.gender(true),
			city: faker.address.city(),
			age: faker.mersenne.rand(100, 18),
			description: faker.lorem.sentence(),
			photo: faker.image.people(240),
		},
		{
			firstName: faker.name.firstName(),
			lastName: faker.name.lastName(),
			email: faker.internet.email(),
			password: faker.internet.password(),
			gender: faker.name.gender(true),
			city: faker.address.city(),
			age: faker.mersenne.rand(100, 18),
			description: faker.lorem.sentence(),
			photo: faker.image.people(240),
		},
		{
			firstName: faker.name.firstName(),
			lastName: faker.name.lastName(),
			email: faker.internet.email(),
			password: faker.internet.password(),
			gender: faker.name.gender(true),
			city: faker.address.city(),
			age: faker.mersenne.rand(100, 18),
			description: faker.lorem.sentence(),
			photo: faker.image.people(240),
		},
		{
			firstName: faker.name.firstName(),
			lastName: faker.name.lastName(),
			email: faker.internet.email(),
			password: faker.internet.password(),
			gender: faker.name.gender(true),
			city: faker.address.city(),
			age: faker.mersenne.rand(100, 18),
			description: faker.lorem.sentence(),
			photo: faker.image.people(240),
		},
		{
			firstName: faker.name.firstName(),
			lastName: faker.name.lastName(),
			email: faker.internet.email(),
			password: faker.internet.password(),
			gender: faker.name.gender(true),
			city: faker.address.city(),
			age: faker.mersenne.rand(100, 18),
			description: faker.lorem.sentence(),
			photo: faker.image.people(240),
		},
		{
			firstName: faker.name.firstName(),
			lastName: faker.name.lastName(),
			email: faker.internet.email(),
			password: faker.internet.password(),
			gender: faker.name.gender(true),
			city: faker.address.city(),
			age: faker.mersenne.rand(100, 18),
			description: faker.lorem.sentence(),
			photo: faker.image.people(240),
		},
		{
			firstName: faker.name.firstName(),
			lastName: faker.name.lastName(),
			email: faker.internet.email(),
			password: faker.internet.password(),
			gender: faker.name.gender(true),
			city: faker.address.city(),
			age: faker.mersenne.rand(100, 18),
			description: faker.lorem.sentence(),
			photo: faker.image.people(240),
		},
		{
			firstName: faker.name.firstName(),
			lastName: faker.name.lastName(),
			email: faker.internet.email(),
			password: faker.internet.password(),
			gender: faker.name.gender(true),
			city: faker.address.city(),
			age: faker.mersenne.rand(100, 18),
			description: faker.lorem.sentence(),
			photo: faker.image.people(240),
		},
		{
			firstName: faker.name.firstName(),
			lastName: faker.name.lastName(),
			email: faker.internet.email(),
			password: faker.internet.password(),
			gender: faker.name.gender(true),
			city: faker.address.city(),
			age: faker.mersenne.rand(100, 18),
			description: faker.lorem.sentence(),
			photo: faker.image.people(240),
		},
		{
			firstName: faker.name.firstName(),
			lastName: faker.name.lastName(),
			email: faker.internet.email(),
			password: faker.internet.password(),
			gender: faker.name.gender(true),
			city: faker.address.city(),
			age: faker.mersenne.rand(100, 18),
			description: faker.lorem.sentence(),
			photo: faker.image.people(240),
		},
		{
			firstName: faker.name.firstName(),
			lastName: faker.name.lastName(),
			email: faker.internet.email(),
			password: faker.internet.password(),
			gender: faker.name.gender(true),
			city: faker.address.city(),
			age: faker.mersenne.rand(100, 18),
			description: faker.lorem.sentence(),
			photo: faker.image.people(240),
		},
		{
			firstName: faker.name.firstName(),
			lastName: faker.name.lastName(),
			email: faker.internet.email(),
			password: faker.internet.password(),
			gender: faker.name.gender(true),
			city: faker.address.city(),
			age: faker.mersenne.rand(100, 18),
			description: faker.lorem.sentence(),
			photo: faker.image.people(240),
		},
		{
			firstName: faker.name.firstName(),
			lastName: faker.name.lastName(),
			email: faker.internet.email(),
			password: faker.internet.password(),
			gender: faker.name.gender(true),
			city: faker.address.city(),
			age: faker.mersenne.rand(100, 18),
			description: faker.lorem.sentence(),
			photo: faker.image.people(240),
		},
		{
			firstName: faker.name.firstName(),
			lastName: faker.name.lastName(),
			email: faker.internet.email(),
			password: faker.internet.password(),
			gender: faker.name.gender(true),
			city: faker.address.city(),
			age: faker.mersenne.rand(100, 18),
			description: faker.lorem.sentence(),
			photo: faker.image.people(240),
		},
		{
			firstName: faker.name.firstName(),
			lastName: faker.name.lastName(),
			email: faker.internet.email(),
			password: faker.internet.password(),
			gender: faker.name.gender(true),
			city: faker.address.city(),
			age: faker.mersenne.rand(100, 18),
			description: faker.lorem.sentence(),
			photo: faker.image.people(240),
		},
		{
			firstName: faker.name.firstName(),
			lastName: faker.name.lastName(),
			email: faker.internet.email(),
			password: faker.internet.password(),
			gender: faker.name.gender(true),
			city: faker.address.city(),
			age: faker.mersenne.rand(100, 18),
			description: faker.lorem.sentence(),
			photo: faker.image.people(240),
		},
	];
	console.log(usersToCreate);
	const users = await User.insertMany(usersToCreate);

	const hobbiesToCreate = [
		{
			hobbyName: faker.word.verb(),
			hobbyAbout: faker.lorem.sentence(),
		},
		{
			hobbyName: faker.word.verb(),
			hobbyAbout: faker.lorem.sentence(),
		},
		{
			hobbyName: faker.word.verb(),
			hobbyAbout: faker.lorem.sentence(),
		},
		{
			hobbyName: faker.word.verb(),
			hobbyAbout: faker.lorem.sentence(),
		},
		{
			hobbyName: faker.word.verb(),
			hobbyAbout: faker.lorem.sentence(),
		},
		{
			hobbyName: faker.word.verb(),
			hobbyAbout: faker.lorem.sentence(),
		},
		{
			hobbyName: faker.word.verb(),
			hobbyAbout: faker.lorem.sentence(),
		},
		{
			hobbyName: faker.word.verb(),
			hobbyAbout: faker.lorem.sentence(),
		},
		{
			hobbyName: faker.word.verb(),
			hobbyAbout: faker.lorem.sentence(),
		},
		{
			hobbyName: faker.word.verb(),
			hobbyAbout: faker.lorem.sentence(),
		},
		{
			hobbyName: faker.word.verb(),
			hobbyAbout: faker.lorem.sentence(),
		},
		{
			hobbyName: faker.word.verb(),
			hobbyAbout: faker.lorem.sentence(),
		},
		{
			hobbyName: faker.word.verb(),
			hobbyAbout: faker.lorem.sentence(),
		},
		{
			hobbyName: faker.word.verb(),
			hobbyAbout: faker.lorem.sentence(),
		},
		{
			hobbyName: faker.word.verb(),
			hobbyAbout: faker.lorem.sentence(),
		},
		{
			hobbyName: faker.word.verb(),
			hobbyAbout: faker.lorem.sentence(),
		},
		{
			hobbyName: faker.word.verb(),
			hobbyAbout: faker.lorem.sentence(),
		},
		{
			hobbyName: faker.word.verb(),
			hobbyAbout: faker.lorem.sentence(),
		},
		{
			hobbyName: faker.word.verb(),
			hobbyAbout: faker.lorem.sentence(),
		},
		{
			hobbyName: faker.word.verb(),
			hobbyAbout: faker.lorem.sentence(),
		},
		{
			hobbyName: faker.word.verb(),
			hobbyAbout: faker.lorem.sentence(),
		},
		{
			hobbyName: faker.word.verb(),
			hobbyAbout: faker.lorem.sentence(),
		},
		{
			hobbyName: faker.word.verb(),
			hobbyAbout: faker.lorem.sentence(),
		},
		{
			hobbyName: faker.word.verb(),
			hobbyAbout: faker.lorem.sentence(),
		},
		{
			hobbyName: faker.word.verb(),
			hobbyAbout: faker.lorem.sentence(),
		},
		{
			hobbyName: faker.word.verb(),
			hobbyAbout: faker.lorem.sentence(),
		},
		{
			hobbyName: faker.word.verb(),
			hobbyAbout: faker.lorem.sentence(),
		},
		{
			hobbyName: faker.word.verb(),
			hobbyAbout: faker.lorem.sentence(),
		},
		{
			hobbyName: faker.word.verb(),
			hobbyAbout: faker.lorem.sentence(),
		},
		{
			hobbyName: faker.word.verb(),
			hobbyAbout: faker.lorem.sentence(),
		},
		{
			hobbyName: faker.word.verb(),
			hobbyAbout: faker.lorem.sentence(),
		},
	];
	console.log(hobbiesToCreate);
	const hobbies = await Hobby.insertMany(hobbiesToCreate);
	console.log("Database Successfully Seeded");

	process.exit(0);
};

seedDb();
